---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-sync-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-sync
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: harbor-sync-data
        persistentVolumeClaim:
          claimName: harbor-sync-volume
      containers:
      - name: manager
        image: quay.io/moolen/harbor-sync:latest
        command:
        - /harbor-sync
        args:
        - controller
        - --store=/data
        - --harbor-poll-interval=2m
        - --force-sync-interval=5m
        - --rotation-interval=10m
        env:
          - name: HARBOR_API_ENDPOINT
            value: http://harbor.example.com
          - name: HARBOR_USERNAME
            value: admin
          - name: HARBOR_PASSWORD
            value: Harbor12345
        volumeMounts:
        - name: harbor-sync-data
          mountPath: /data
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
