---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-sync
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        image: docker.io/moolen/harbor-sync:latest
        command:
        - /harbor-sync-controller
        args:
        - -harbor-poll-interval=2m
        - -force-sync-interval=5m
        env:
          - name: HARBOR_API_ENDPOINT
            value: http://harbor.example.com
          - name: HARBOR_USERNAME
            value: admin
          - name: HARBOR_PASSWORD
            value: Harbor12345
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
