apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harbor-sync-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harbor-sync
subjects:
- kind: ServiceAccount
  name: harbor-sync
  namespace: default
