apiVersion: crd.harborsync.k8s.io/v1
kind: HarborSync
metadata:
  name: harborsync-sample
spec:
  type: Regex
  name: team-(foo|bar|baz|bang)
  robotAccountSuffix: k8s-robot
  mapping:
  - type: Translate
    namespace: team-$1 # references harbor project name from above: team-foo, team-bar, ...
    secret: $1-pull-secret # foo-pull-secret, bar-pull-secret, ...
