name: Run Tests

on:
  push:
    branches:
    - master
  pull_request:

env:
  GO_VERSION: '1.16'
  # list of available versions: https://storage.googleapis.com/kubebuilder-tools
  # TODO: 1.21.2 does not shut down properly with controller-runtime 0.9.2
  KUBEBUILDER_TOOLS_VERSION: '1.20.2'

jobs:

  test:

    name: Test
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Add envtest binaries
      run:  |
        curl -sSLo envtest-bins.tar.gz "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-${{env.KUBEBUILDER_TOOLS_VERSION}}-linux-amd64.tar.gz"
        sudo mkdir -p /usr/local/kubebuilder
        sudo tar -C /usr/local/kubebuilder --strip-components=1 -zvxf envtest-bins.tar.gz
    - name: Cache envtest binaries
      uses: actions/cache@v2.1.6
      with:
        path: /usr/local/kubebuilder
        key: ${{ runner.os }}-kubebuilder-${{env.KUBEBUILDER_TOOLS_VERSION}}
        restore-keys: ${{ runner.os }}-kubebuilder

    - name: Install make
      run: sudo apt-get install -y make

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: make test
